version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - misspell
  disable:
    - depguard
    - exhaustruct

formatters:
  enable:
    - gofmt
    - goimports
