CREATE TABLE forwarding_rules (
    id UUID PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    owner_id UUID NOT NULL REFERENCES users(id),
    mode VARCHAR(20) NOT NULL,
    ingress_node_id UUID NOT NULL REFERENCES node_agents(id),
    ingress_port INTEGER NOT NULL,
    egress_node_id UUID REFERENCES node_agents(id),
    lb_group_id UUID REFERENCES lb_groups(id),
    hop_chain_id UUID REFERENCES hop_chains(id),
    target_host VARCHAR(255) NOT NULL,
    target_port INTEGER NOT NULL,
    status VARCHAR(20) DEFAULT 'stopped',
    sync_status VARCHAR(20) DEFAULT 'pending_sync',
    instance_info JSONB,
    np_tls SMALLINT,
    np_mode VARCHAR(10),
    np_min INTEGER,
    np_max INTEGER,
    np_rate INTEGER,
    np_notcp BOOLEAN,
    np_noudp BOOLEAN,
    np_log VARCHAR(10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
