name: Bug Report
description: 报告一个可复现的问题
title: "[Bug] "
labels:
  - bug
body:
  - type: input
    id: version
    attributes:
      label: 版本号
      description: 请输入 Hub/Frontend/Agent 版本信息
      placeholder: v0.1.0
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: 重现步骤
      description: 请提供可以稳定复现问题的步骤
      placeholder: |
        1. 打开 ...
        2. 点击 ...
        3. 观察 ...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 预期行为
      description: 你期望系统表现为何
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: 实际行为
      description: 实际发生了什么
    validations:
      required: true

  - type: textarea
    id: logs_or_screenshot
    attributes:
      label: 日志截图
      description: 粘贴关键日志、错误堆栈或截图
      placeholder: 拖拽截图或粘贴日志
    validations:
      required: false
